// Autogenerated from Pigeon (v22.7.4), do not edit directly.
// See also: https://pub.dev/packages/pigeon
@file:Suppress("UNCHECKED_CAST", "ArrayInDataClass")

package com.caprado.romgi.seven_zip

import android.util.Log
import io.flutter.plugin.common.BasicMessageChannel
import io.flutter.plugin.common.BinaryMessenger
import io.flutter.plugin.common.EventChannel
import io.flutter.plugin.common.MessageCodec
import io.flutter.plugin.common.StandardMethodCodec
import io.flutter.plugin.common.StandardMessageCodec
import java.io.ByteArrayOutputStream
import java.nio.ByteBuffer

private fun wrapResult(result: Any?): List<Any?> {
  return listOf(result)
}

private fun wrapError(exception: Throwable): List<Any?> {
  return if (exception is FlutterError) {
    listOf(
      exception.code,
      exception.message,
      exception.details
    )
  } else {
    listOf(
      exception.javaClass.simpleName,
      exception.toString(),
      "Cause: " + exception.cause + ", Stacktrace: " + Log.getStackTraceString(exception)
    )
  }
}

private fun createConnectionError(channelName: String): FlutterError {
  return FlutterError("channel-error",  "Unable to establish connection on channel: '$channelName'.", "")}

/**
 * Error class for passing custom error details to Flutter via a thrown PlatformException.
 * @property code The error code.
 * @property message The error message.
 * @property details The error details. Must be a datatype supported by the api codec.
 */
class FlutterError (
  val code: String,
  override val message: String? = null,
  val details: Any? = null
) : Throwable()

/**
 * Live progress of a 7z extraction.
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class ExtractionProgress (
  /** The archive being extracted. */
  val archivePath: String,
  /** Bytes extracted so far. */
  val bytesExtracted: Long,
  /** Total uncompressed size in bytes. -1 if unknown. */
  val totalBytes: Long
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): ExtractionProgress {
      val archivePath = pigeonVar_list[0] as String
      val bytesExtracted = pigeonVar_list[1] as Long
      val totalBytes = pigeonVar_list[2] as Long
      return ExtractionProgress(archivePath, bytesExtracted, totalBytes)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      archivePath,
      bytesExtracted,
      totalBytes,
    )
  }
}
private open class SevenZipApiPigeonCodec : StandardMessageCodec() {
  override fun readValueOfType(type: Byte, buffer: ByteBuffer): Any? {
    return when (type) {
      129.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          ExtractionProgress.fromList(it)
        }
      }
      else -> super.readValueOfType(type, buffer)
    }
  }
  override fun writeValue(stream: ByteArrayOutputStream, value: Any?)   {
    when (value) {
      is ExtractionProgress -> {
        stream.write(129)
        writeValue(stream, value.toList())
      }
      else -> super.writeValue(stream, value)
    }
  }
}


/**
 * Methods Dart calls into Kotlin.
 *
 * Generated interface from Pigeon that represents a handler of messages from Flutter.
 */
interface SevenZipHostApi {
  /**
   * Extract a 7z archive to the given output directory.
   * Returns the path to the extracted file (or directory if multiple files).
   */
  fun extract(archivePath: String, outputDir: String, callback: (Result<String>) -> Unit)
  /** Cancel an in-progress extraction. */
  fun cancel(archivePath: String)

  companion object {
    /** The codec used by SevenZipHostApi. */
    val codec: MessageCodec<Any?> by lazy {
      SevenZipApiPigeonCodec()
    }
    /** Sets up an instance of `SevenZipHostApi` to handle messages through the `binaryMessenger`. */
    @JvmOverloads
    fun setUp(binaryMessenger: BinaryMessenger, api: SevenZipHostApi?, messageChannelSuffix: String = "") {
      val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.romgi.SevenZipHostApi.extract$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val archivePathArg = args[0] as String
            val outputDirArg = args[1] as String
            api.extract(archivePathArg, outputDirArg) { result: Result<String> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.romgi.SevenZipHostApi.cancel$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val archivePathArg = args[0] as String
            val wrapped: List<Any?> = try {
              api.cancel(archivePathArg)
              listOf(null)
            } catch (exception: Throwable) {
              wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
    }
  }
}
/**
 * Methods Kotlin calls into Dart. Push-style progress updates.
 *
 * Generated class from Pigeon that represents Flutter messages that can be called from Kotlin.
 */
class SevenZipEvents(private val binaryMessenger: BinaryMessenger, private val messageChannelSuffix: String = "") {
  companion object {
    /** The codec used by SevenZipEvents. */
    val codec: MessageCodec<Any?> by lazy {
      SevenZipApiPigeonCodec()
    }
  }
  fun onProgress(progressArg: ExtractionProgress, callback: (Result<Unit>) -> Unit)
{
    val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
    val channelName = "dev.flutter.pigeon.romgi.SevenZipEvents.onProgress$separatedMessageChannelSuffix"
    val channel = BasicMessageChannel<Any?>(binaryMessenger, channelName, codec)
    channel.send(listOf(progressArg)) {
      if (it is List<*>) {
        if (it.size > 1) {
          callback(Result.failure(FlutterError(it[0] as String, it[1] as String, it[2] as String?)))
        } else {
          callback(Result.success(Unit))
        }
      } else {
        callback(Result.failure(createConnectionError(channelName)))
      } 
    }
  }
}
