// Autogenerated from Pigeon (v22.7.4), do not edit directly.
// See also: https://pub.dev/packages/pigeon
// ignore_for_file: public_member_api_docs, non_constant_identifier_names, avoid_as, unused_import, unnecessary_parenthesis, prefer_null_aware_operators, omit_local_variable_types, unused_shown_name, unnecessary_import, no_leading_underscores_for_local_identifiers

import 'dart:async';
import 'dart:typed_data' show Float64List, Int32List, Int64List, Uint8List;

import 'package:flutter/foundation.dart' show ReadBuffer, WriteBuffer;
import 'package:flutter/services.dart';

PlatformException _createConnectionError(String channelName) {
  return PlatformException(
    code: 'channel-error',
    message: 'Unable to establish connection on channel: "$channelName".',
  );
}

List<Object?> wrapResponse({Object? result, PlatformException? error, bool empty = false}) {
  if (empty) {
    return <Object?>[];
  }
  if (error == null) {
    return <Object?>[result];
  }
  return <Object?>[error.code, error.message, error.details];
}

/// One file inside a torrent.
class TorrentFile {
  TorrentFile({
    required this.index,
    required this.path,
    required this.length,
    required this.bytesDownloaded,
    required this.priority,
  });

  /// Position in the torrent's file list. Stable across sessions.
  int index;

  /// Path inside the torrent (forward slashes, no leading slash).
  String path;

  /// Total file size in bytes.
  int length;

  /// How much of this file is on disk.
  int bytesDownloaded;

  /// libtorrent priority. 0 = don't download, 1..7 = increasing.
  int priority;

  Object encode() {
    return <Object?>[
      index,
      path,
      length,
      bytesDownloaded,
      priority,
    ];
  }

  static TorrentFile decode(Object result) {
    result as List<Object?>;
    return TorrentFile(
      index: result[0]! as int,
      path: result[1]! as String,
      length: result[2]! as int,
      bytesDownloaded: result[3]! as int,
      priority: result[4]! as int,
    );
  }
}

/// Live state of a single torrent. Streamed via [TorrentEvents].
class TorrentProgress {
  TorrentProgress({
    required this.infohash,
    required this.name,
    required this.state,
    required this.totalSize,
    required this.bytesDownloaded,
    required this.downloadRate,
    required this.uploadRate,
    required this.peers,
    required this.seeds,
    required this.error,
    required this.files,
  });

  String infohash;

  String name;

  /// One of: queued, checking_files, downloading_metadata, downloading,
  /// finished, seeding, allocating, paused, error, unknown.
  String state;

  int totalSize;

  int bytesDownloaded;

  /// Bytes/sec.
  int downloadRate;

  int uploadRate;

  int peers;

  int seeds;

  /// Empty when no error.
  String error;

  /// Per-file progress. Snapshot at the moment of emission.
  List<TorrentFile> files;

  Object encode() {
    return <Object?>[
      infohash,
      name,
      state,
      totalSize,
      bytesDownloaded,
      downloadRate,
      uploadRate,
      peers,
      seeds,
      error,
      files,
    ];
  }

  static TorrentProgress decode(Object result) {
    result as List<Object?>;
    return TorrentProgress(
      infohash: result[0]! as String,
      name: result[1]! as String,
      state: result[2]! as String,
      totalSize: result[3]! as int,
      bytesDownloaded: result[4]! as int,
      downloadRate: result[5]! as int,
      uploadRate: result[6]! as int,
      peers: result[7]! as int,
      seeds: result[8]! as int,
      error: result[9]! as String,
      files: (result[10] as List<Object?>?)!.cast<TorrentFile>(),
    );
  }
}

/// Configuration for the torrent session.
class TorrentSettings {
  TorrentSettings({
    required this.savePath,
    required this.seedingEnabled,
    required this.dhtEnabled,
    required this.maxConnections,
    required this.maxUploads,
    required this.maxDownloadRateBytesPerSec,
    required this.maxUploadRateBytesPerSec,
  });

  /// Where torrent payloads are written. App-private; the
  /// TorrentAdapter moves completed files into the per-platform Roms folder.
  String savePath;

  /// When false, the session stops uploading the moment a torrent
  /// completes. Default true.
  bool seedingEnabled;

  /// DHT for trackerless peer discovery. Default true.
  bool dhtEnabled;

  int maxConnections;

  int maxUploads;

  int maxDownloadRateBytesPerSec;

  int maxUploadRateBytesPerSec;

  Object encode() {
    return <Object?>[
      savePath,
      seedingEnabled,
      dhtEnabled,
      maxConnections,
      maxUploads,
      maxDownloadRateBytesPerSec,
      maxUploadRateBytesPerSec,
    ];
  }

  static TorrentSettings decode(Object result) {
    result as List<Object?>;
    return TorrentSettings(
      savePath: result[0]! as String,
      seedingEnabled: result[1]! as bool,
      dhtEnabled: result[2]! as bool,
      maxConnections: result[3]! as int,
      maxUploads: result[4]! as int,
      maxDownloadRateBytesPerSec: result[5]! as int,
      maxUploadRateBytesPerSec: result[6]! as int,
    );
  }
}

/// Request to add a torrent. At least one of [magnet]/[torrentBytes]
/// must be set; [magnet] wins when both are present.
class AddTorrentRequest {
  AddTorrentRequest({
    this.magnet,
    this.torrentBytes,
    required this.fileIndices,
  });

  String? magnet;

  /// Raw .torrent bytes. Honoured when [magnet] is null.
  Uint8List? torrentBytes;

  /// File indices to download. Every other file's priority is set to 0.
  /// An empty list means "download all".
  List<int> fileIndices;

  Object encode() {
    return <Object?>[
      magnet,
      torrentBytes,
      fileIndices,
    ];
  }

  static AddTorrentRequest decode(Object result) {
    result as List<Object?>;
    return AddTorrentRequest(
      magnet: result[0] as String?,
      torrentBytes: result[1] as Uint8List?,
      fileIndices: (result[2] as List<Object?>?)!.cast<int>(),
    );
  }
}


class _PigeonCodec extends StandardMessageCodec {
  const _PigeonCodec();
  @override
  void writeValue(WriteBuffer buffer, Object? value) {
    if (value is int) {
      buffer.putUint8(4);
      buffer.putInt64(value);
    }    else if (value is TorrentFile) {
      buffer.putUint8(129);
      writeValue(buffer, value.encode());
    }    else if (value is TorrentProgress) {
      buffer.putUint8(130);
      writeValue(buffer, value.encode());
    }    else if (value is TorrentSettings) {
      buffer.putUint8(131);
      writeValue(buffer, value.encode());
    }    else if (value is AddTorrentRequest) {
      buffer.putUint8(132);
      writeValue(buffer, value.encode());
    } else {
      super.writeValue(buffer, value);
    }
  }

  @override
  Object? readValueOfType(int type, ReadBuffer buffer) {
    switch (type) {
      case 129: 
        return TorrentFile.decode(readValue(buffer)!);
      case 130: 
        return TorrentProgress.decode(readValue(buffer)!);
      case 131: 
        return TorrentSettings.decode(readValue(buffer)!);
      case 132: 
        return AddTorrentRequest.decode(readValue(buffer)!);
      default:
        return super.readValueOfType(type, buffer);
    }
  }
}

/// Methods Dart calls into Kotlin.
class TorrentHostApi {
  /// Constructor for [TorrentHostApi].  The [binaryMessenger] named argument is
  /// available for dependency injection.  If it is left null, the default
  /// BinaryMessenger will be used which routes to the host platform.
  TorrentHostApi({BinaryMessenger? binaryMessenger, String messageChannelSuffix = ''})
      : pigeonVar_binaryMessenger = binaryMessenger,
        pigeonVar_messageChannelSuffix = messageChannelSuffix.isNotEmpty ? '.$messageChannelSuffix' : '';
  final BinaryMessenger? pigeonVar_binaryMessenger;

  static const MessageCodec<Object?> pigeonChannelCodec = _PigeonCodec();

  final String pigeonVar_messageChannelSuffix;

  /// Idempotent. Called from app bootstrap before any other method.
  Future<void> start(TorrentSettings settings) async {
    final String pigeonVar_channelName = 'dev.flutter.pigeon.romgi.TorrentHostApi.start$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_channel.send(<Object?>[settings]) as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else {
      return;
    }
  }

  Future<void> updateSettings(TorrentSettings settings) async {
    final String pigeonVar_channelName = 'dev.flutter.pigeon.romgi.TorrentHostApi.updateSettings$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_channel.send(<Object?>[settings]) as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else {
      return;
    }
  }

  /// Adds the torrent and returns its infohash. If the torrent is already
  /// in the session, file priorities are *unioned* with [request.fileIndices]
  /// — a previously-zero file gets pulled in without losing existing ones.
  Future<String> addTorrent(AddTorrentRequest request) async {
    final String pigeonVar_channelName = 'dev.flutter.pigeon.romgi.TorrentHostApi.addTorrent$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_channel.send(<Object?>[request]) as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else if (pigeonVar_replyList[0] == null) {
      throw PlatformException(
        code: 'null-error',
        message: 'Host platform returned null value for non-null return value.',
      );
    } else {
      return (pigeonVar_replyList[0] as String?)!;
    }
  }

  Future<void> cancel(String infohash) async {
    final String pigeonVar_channelName = 'dev.flutter.pigeon.romgi.TorrentHostApi.cancel$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_channel.send(<Object?>[infohash]) as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else {
      return;
    }
  }

  Future<void> pauseAll() async {
    final String pigeonVar_channelName = 'dev.flutter.pigeon.romgi.TorrentHostApi.pauseAll$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_channel.send(null) as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else {
      return;
    }
  }

  Future<void> resumeAll() async {
    final String pigeonVar_channelName = 'dev.flutter.pigeon.romgi.TorrentHostApi.resumeAll$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_channel.send(null) as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else {
      return;
    }
  }

  /// One-shot snapshot. Useful for UI on cold start; ongoing updates
  /// arrive via [TorrentEvents.onProgress].
  Future<List<TorrentProgress>> listAll() async {
    final String pigeonVar_channelName = 'dev.flutter.pigeon.romgi.TorrentHostApi.listAll$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_channel.send(null) as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else if (pigeonVar_replyList[0] == null) {
      throw PlatformException(
        code: 'null-error',
        message: 'Host platform returned null value for non-null return value.',
      );
    } else {
      return (pigeonVar_replyList[0] as List<Object?>?)!.cast<TorrentProgress>();
    }
  }
}

/// Methods Kotlin calls into Dart. Push-style updates from the runtime.
abstract class TorrentEvents {
  static const MessageCodec<Object?> pigeonChannelCodec = _PigeonCodec();

  void onProgress(TorrentProgress progress);

  void onError(String infohash, String error);

  static void setUp(TorrentEvents? api, {BinaryMessenger? binaryMessenger, String messageChannelSuffix = '',}) {
    messageChannelSuffix = messageChannelSuffix.isNotEmpty ? '.$messageChannelSuffix' : '';
    {
      final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
          'dev.flutter.pigeon.romgi.TorrentEvents.onProgress$messageChannelSuffix', pigeonChannelCodec,
          binaryMessenger: binaryMessenger);
      if (api == null) {
        pigeonVar_channel.setMessageHandler(null);
      } else {
        pigeonVar_channel.setMessageHandler((Object? message) async {
          assert(message != null,
          'Argument for dev.flutter.pigeon.romgi.TorrentEvents.onProgress was null.');
          final List<Object?> args = (message as List<Object?>?)!;
          final TorrentProgress? arg_progress = (args[0] as TorrentProgress?);
          assert(arg_progress != null,
              'Argument for dev.flutter.pigeon.romgi.TorrentEvents.onProgress was null, expected non-null TorrentProgress.');
          try {
            api.onProgress(arg_progress!);
            return wrapResponse(empty: true);
          } on PlatformException catch (e) {
            return wrapResponse(error: e);
          }          catch (e) {
            return wrapResponse(error: PlatformException(code: 'error', message: e.toString()));
          }
        });
      }
    }
    {
      final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
          'dev.flutter.pigeon.romgi.TorrentEvents.onError$messageChannelSuffix', pigeonChannelCodec,
          binaryMessenger: binaryMessenger);
      if (api == null) {
        pigeonVar_channel.setMessageHandler(null);
      } else {
        pigeonVar_channel.setMessageHandler((Object? message) async {
          assert(message != null,
          'Argument for dev.flutter.pigeon.romgi.TorrentEvents.onError was null.');
          final List<Object?> args = (message as List<Object?>?)!;
          final String? arg_infohash = (args[0] as String?);
          assert(arg_infohash != null,
              'Argument for dev.flutter.pigeon.romgi.TorrentEvents.onError was null, expected non-null String.');
          final String? arg_error = (args[1] as String?);
          assert(arg_error != null,
              'Argument for dev.flutter.pigeon.romgi.TorrentEvents.onError was null, expected non-null String.');
          try {
            api.onError(arg_infohash!, arg_error!);
            return wrapResponse(empty: true);
          } on PlatformException catch (e) {
            return wrapResponse(error: e);
          }          catch (e) {
            return wrapResponse(error: PlatformException(code: 'error', message: e.toString()));
          }
        });
      }
    }
  }
}
