// Autogenerated from Pigeon (v22.7.4), do not edit directly.
// See also: https://pub.dev/packages/pigeon
@file:Suppress("UNCHECKED_CAST", "ArrayInDataClass")

package com.caprado.romgi.torrent

import android.util.Log
import io.flutter.plugin.common.BasicMessageChannel
import io.flutter.plugin.common.BinaryMessenger
import io.flutter.plugin.common.EventChannel
import io.flutter.plugin.common.MessageCodec
import io.flutter.plugin.common.StandardMethodCodec
import io.flutter.plugin.common.StandardMessageCodec
import java.io.ByteArrayOutputStream
import java.nio.ByteBuffer

private fun wrapResult(result: Any?): List<Any?> {
  return listOf(result)
}

private fun wrapError(exception: Throwable): List<Any?> {
  return if (exception is FlutterError) {
    listOf(
      exception.code,
      exception.message,
      exception.details
    )
  } else {
    listOf(
      exception.javaClass.simpleName,
      exception.toString(),
      "Cause: " + exception.cause + ", Stacktrace: " + Log.getStackTraceString(exception)
    )
  }
}

private fun createConnectionError(channelName: String): FlutterError {
  return FlutterError("channel-error",  "Unable to establish connection on channel: '$channelName'.", "")}

/**
 * Error class for passing custom error details to Flutter via a thrown PlatformException.
 * @property code The error code.
 * @property message The error message.
 * @property details The error details. Must be a datatype supported by the api codec.
 */
class FlutterError (
  val code: String,
  override val message: String? = null,
  val details: Any? = null
) : Throwable()

/**
 * One file inside a torrent.
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class TorrentFile (
  /** Position in the torrent's file list. Stable across sessions. */
  val index: Long,
  /** Path inside the torrent (forward slashes, no leading slash). */
  val path: String,
  /** Total file size in bytes. */
  val length: Long,
  /** How much of this file is on disk. */
  val bytesDownloaded: Long,
  /** libtorrent priority. 0 = don't download, 1..7 = increasing. */
  val priority: Long
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): TorrentFile {
      val index = pigeonVar_list[0] as Long
      val path = pigeonVar_list[1] as String
      val length = pigeonVar_list[2] as Long
      val bytesDownloaded = pigeonVar_list[3] as Long
      val priority = pigeonVar_list[4] as Long
      return TorrentFile(index, path, length, bytesDownloaded, priority)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      index,
      path,
      length,
      bytesDownloaded,
      priority,
    )
  }
}

/**
 * Live state of a single torrent. Streamed via [TorrentEvents].
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class TorrentProgress (
  val infohash: String,
  val name: String,
  /**
   * One of: queued, checking_files, downloading_metadata, downloading,
   * finished, seeding, allocating, paused, error, unknown.
   */
  val state: String,
  val totalSize: Long,
  val bytesDownloaded: Long,
  /** Bytes/sec. */
  val downloadRate: Long,
  val uploadRate: Long,
  val peers: Long,
  val seeds: Long,
  /** Empty when no error. */
  val error: String,
  /** Per-file progress. Snapshot at the moment of emission. */
  val files: List<TorrentFile>
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): TorrentProgress {
      val infohash = pigeonVar_list[0] as String
      val name = pigeonVar_list[1] as String
      val state = pigeonVar_list[2] as String
      val totalSize = pigeonVar_list[3] as Long
      val bytesDownloaded = pigeonVar_list[4] as Long
      val downloadRate = pigeonVar_list[5] as Long
      val uploadRate = pigeonVar_list[6] as Long
      val peers = pigeonVar_list[7] as Long
      val seeds = pigeonVar_list[8] as Long
      val error = pigeonVar_list[9] as String
      val files = pigeonVar_list[10] as List<TorrentFile>
      return TorrentProgress(infohash, name, state, totalSize, bytesDownloaded, downloadRate, uploadRate, peers, seeds, error, files)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      infohash,
      name,
      state,
      totalSize,
      bytesDownloaded,
      downloadRate,
      uploadRate,
      peers,
      seeds,
      error,
      files,
    )
  }
}

/**
 * Configuration for the torrent session.
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class TorrentSettings (
  /**
   * Where torrent payloads are written. App-private; the
   * TorrentAdapter moves completed files into the per-platform Roms folder.
   */
  val savePath: String,
  /**
   * When false, the session stops uploading the moment a torrent
   * completes. Default true.
   */
  val seedingEnabled: Boolean,
  /** DHT for trackerless peer discovery. Default true. */
  val dhtEnabled: Boolean,
  val maxConnections: Long,
  val maxUploads: Long,
  val maxDownloadRateBytesPerSec: Long,
  val maxUploadRateBytesPerSec: Long
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): TorrentSettings {
      val savePath = pigeonVar_list[0] as String
      val seedingEnabled = pigeonVar_list[1] as Boolean
      val dhtEnabled = pigeonVar_list[2] as Boolean
      val maxConnections = pigeonVar_list[3] as Long
      val maxUploads = pigeonVar_list[4] as Long
      val maxDownloadRateBytesPerSec = pigeonVar_list[5] as Long
      val maxUploadRateBytesPerSec = pigeonVar_list[6] as Long
      return TorrentSettings(savePath, seedingEnabled, dhtEnabled, maxConnections, maxUploads, maxDownloadRateBytesPerSec, maxUploadRateBytesPerSec)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      savePath,
      seedingEnabled,
      dhtEnabled,
      maxConnections,
      maxUploads,
      maxDownloadRateBytesPerSec,
      maxUploadRateBytesPerSec,
    )
  }
}

/**
 * Request to add a torrent. At least one of [magnet]/[torrentBytes]
 * must be set; [magnet] wins when both are present.
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class AddTorrentRequest (
  val magnet: String? = null,
  /** Raw .torrent bytes. Honoured when [magnet] is null. */
  val torrentBytes: ByteArray? = null,
  /**
   * File indices to download. Every other file's priority is set to 0.
   * An empty list means "download all".
   */
  val fileIndices: List<Long>
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): AddTorrentRequest {
      val magnet = pigeonVar_list[0] as String?
      val torrentBytes = pigeonVar_list[1] as ByteArray?
      val fileIndices = pigeonVar_list[2] as List<Long>
      return AddTorrentRequest(magnet, torrentBytes, fileIndices)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      magnet,
      torrentBytes,
      fileIndices,
    )
  }
}
private open class TorrentApiPigeonCodec : StandardMessageCodec() {
  override fun readValueOfType(type: Byte, buffer: ByteBuffer): Any? {
    return when (type) {
      129.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          TorrentFile.fromList(it)
        }
      }
      130.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          TorrentProgress.fromList(it)
        }
      }
      131.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          TorrentSettings.fromList(it)
        }
      }
      132.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          AddTorrentRequest.fromList(it)
        }
      }
      else -> super.readValueOfType(type, buffer)
    }
  }
  override fun writeValue(stream: ByteArrayOutputStream, value: Any?)   {
    when (value) {
      is TorrentFile -> {
        stream.write(129)
        writeValue(stream, value.toList())
      }
      is TorrentProgress -> {
        stream.write(130)
        writeValue(stream, value.toList())
      }
      is TorrentSettings -> {
        stream.write(131)
        writeValue(stream, value.toList())
      }
      is AddTorrentRequest -> {
        stream.write(132)
        writeValue(stream, value.toList())
      }
      else -> super.writeValue(stream, value)
    }
  }
}

/**
 * Methods Dart calls into Kotlin.
 *
 * Generated interface from Pigeon that represents a handler of messages from Flutter.
 */
interface TorrentHostApi {
  /** Idempotent. Called from app bootstrap before any other method. */
  fun start(settings: TorrentSettings)
  fun updateSettings(settings: TorrentSettings)
  /**
   * Adds the torrent and returns its infohash. If the torrent is already
   * in the session, file priorities are *unioned* with [request.fileIndices]
   * — a previously-zero file gets pulled in without losing existing ones.
   */
  fun addTorrent(request: AddTorrentRequest): String
  fun cancel(infohash: String)
  fun pauseAll()
  fun resumeAll()
  /**
   * One-shot snapshot. Useful for UI on cold start; ongoing updates
   * arrive via [TorrentEvents.onProgress].
   */
  fun listAll(): List<TorrentProgress>

  companion object {
    /** The codec used by TorrentHostApi. */
    val codec: MessageCodec<Any?> by lazy {
      TorrentApiPigeonCodec()
    }
    /** Sets up an instance of `TorrentHostApi` to handle messages through the `binaryMessenger`. */
    @JvmOverloads
    fun setUp(binaryMessenger: BinaryMessenger, api: TorrentHostApi?, messageChannelSuffix: String = "") {
      val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.romgi.TorrentHostApi.start$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val settingsArg = args[0] as TorrentSettings
            val wrapped: List<Any?> = try {
              api.start(settingsArg)
              listOf(null)
            } catch (exception: Throwable) {
              wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.romgi.TorrentHostApi.updateSettings$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val settingsArg = args[0] as TorrentSettings
            val wrapped: List<Any?> = try {
              api.updateSettings(settingsArg)
              listOf(null)
            } catch (exception: Throwable) {
              wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.romgi.TorrentHostApi.addTorrent$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val requestArg = args[0] as AddTorrentRequest
            val wrapped: List<Any?> = try {
              listOf(api.addTorrent(requestArg))
            } catch (exception: Throwable) {
              wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.romgi.TorrentHostApi.cancel$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val infohashArg = args[0] as String
            val wrapped: List<Any?> = try {
              api.cancel(infohashArg)
              listOf(null)
            } catch (exception: Throwable) {
              wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.romgi.TorrentHostApi.pauseAll$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              api.pauseAll()
              listOf(null)
            } catch (exception: Throwable) {
              wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.romgi.TorrentHostApi.resumeAll$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              api.resumeAll()
              listOf(null)
            } catch (exception: Throwable) {
              wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.romgi.TorrentHostApi.listAll$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              listOf(api.listAll())
            } catch (exception: Throwable) {
              wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
    }
  }
}
/**
 * Methods Kotlin calls into Dart. Push-style updates from the runtime.
 *
 * Generated class from Pigeon that represents Flutter messages that can be called from Kotlin.
 */
class TorrentEvents(private val binaryMessenger: BinaryMessenger, private val messageChannelSuffix: String = "") {
  companion object {
    /** The codec used by TorrentEvents. */
    val codec: MessageCodec<Any?> by lazy {
      TorrentApiPigeonCodec()
    }
  }
  fun onProgress(progressArg: TorrentProgress, callback: (Result<Unit>) -> Unit)
{
    val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
    val channelName = "dev.flutter.pigeon.romgi.TorrentEvents.onProgress$separatedMessageChannelSuffix"
    val channel = BasicMessageChannel<Any?>(binaryMessenger, channelName, codec)
    channel.send(listOf(progressArg)) {
      if (it is List<*>) {
        if (it.size > 1) {
          callback(Result.failure(FlutterError(it[0] as String, it[1] as String, it[2] as String?)))
        } else {
          callback(Result.success(Unit))
        }
      } else {
        callback(Result.failure(createConnectionError(channelName)))
      } 
    }
  }
  fun onError(infohashArg: String, errorArg: String, callback: (Result<Unit>) -> Unit)
{
    val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
    val channelName = "dev.flutter.pigeon.romgi.TorrentEvents.onError$separatedMessageChannelSuffix"
    val channel = BasicMessageChannel<Any?>(binaryMessenger, channelName, codec)
    channel.send(listOf(infohashArg, errorArg)) {
      if (it is List<*>) {
        if (it.size > 1) {
          callback(Result.failure(FlutterError(it[0] as String, it[1] as String, it[2] as String?)))
        } else {
          callback(Result.success(Unit))
        }
      } else {
        callback(Result.failure(createConnectionError(channelName)))
      } 
    }
  }
}
